In [72]:
import numpy as np

In [44]:
B = np.ndarray(shape=(10),dtype=float)
A = np.ndarray(shape=(10),dtype=float)

In [45]:
B[:] = 1. 
np.shape(B)

(10,)

In [46]:
B=B[np.newaxis,:]
B[:,:]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [40]:
A=A[:,np.newaxis]
A[:,:]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

$$
A_i^{ \:j}
$$
$$C = A \cdot B \rightarrow c_{00} = \sum_{i=0}^{N}a_{0i}b_{i0}$$
$$C_i^{\:k} = A_{i}^{\:j}B_{j}^{\:k}$$

$$
A_{i,j} \cdot B_{j,k} = 
\begin{pmatrix}
a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
\vdots  & \vdots  & \ddots & \vdots  \\
a_{m,1} & a_{m,2} & \cdots & a_{m,n} 
\end{pmatrix} \cdot 
\begin{pmatrix}
b_{1,1} & b_{1,2} & \cdots & b_{1,n} \\
b_{2,1} & b_{2,2} & \cdots & b_{2,n} \\
\vdots  & \vdots  & \ddots & \vdots  \\
b_{m,1} & b_{m,2} & \cdots & b_{m,n} 
\end{pmatrix}
$$

In [47]:
A=np.array([['a00','a01'],['a10','a11']])
B=np.array([['b00','b01'],['b10','b11']])

In [50]:
print(A)
print(B)

[['a00' 'a01']
 ['a10' 'a11']]
[['b00' 'b01']
 ['b10' 'b11']]


https://numpy.org/doc/stable/reference/generated/numpy.einsum.html?highlight=einsum#numpy.einsum

In [52]:
a = np.arange(25).reshape(5,5)
b = np.arange(5)
c = np.arange(6).reshape(2,3)
print(a,b,c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] [0 1 2 3 4] [[0 1 2]
 [3 4 5]]


In [54]:
print(np.einsum('ii', a))
print(np.einsum(a, [0,0]))
print(np.trace(a))

60
60
60


$$ tr(A) = \sum_{i=0}^{N}a_i^{\:i} = A_i^{\:i} $$

In [55]:
print(np.diag(a))
print(np.einsum('ii->i', a))

[ 0  6 12 18 24]
[ 0  6 12 18 24]


In [70]:
z = np.arange(27).reshape(3,3,3)
print(np.sum(z,axis=0))
print(np.einsum('ijk->jk',z))

[[27 30 33]
 [36 39 42]
 [45 48 51]]
[[27 30 33]
 [36 39 42]
 [45 48 51]]


In [66]:
print(np.sum(a, axis=1))
print(np.einsum('ij->i', a))

[ 10  35  60  85 110]
[ 10  35  60  85 110]


In [63]:
a[:,0]
print(np.mean(a,axis=0))

[10. 11. 12. 13. 14.]
