# Libreria Numpy

Nella documentazione ufficiale:
- Quickstart, per iniziare a smanettare da subito: https://numpy.org/doc/stable/user/quickstart.html
- Tutorial più completo con approccio teorico: https://numpy.org/doc/stable/user/absolute_beginners.html 

In [1]:
import numpy as np

In [8]:
# Prima prova semplice

a = np.arange(10)
print(np.shape(a)) # equivalente a a.shape
print(a)
print(type(a))

a2 = a[:,np.newaxis]
print(a2)
print(a2.shape)

print(a[2])
print(a2[2,0])

(10,)
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)
2
2


In [23]:
b = np.arange(10)
c = np.arange(10)

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(type(a))

print('prendo un solo elemento nella posizione 1,1',a[1,1])
print('prendo la riga 0', a[0,:])
print('prendo la colonna 0',a[:,0])
print('è equivalente a prendere la riga 0 - numpy salva gli array row-wise',a[1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
prendo un solo elemento nella posizione 1,1 6
prendo la riga 0 [1 2 3 4]
prendo la colonna 0 [1 5 9]
è equivalente a prendere la riga 0 - numpy salva gli array row-wise [5 6 7 8]


# Creare Array 

In [36]:
array_per_elementi = np.array([1,2,3,4]) # o la sua variante N-dimensionale
array_unitario = np.ones(6) # crea un array di 1 con dimensione 6
print(array_unitario)
matrice_unit = np.ones([6,6])
print(matrice_unit)

array_nullo = np.zeros(6) # crea un array di 0
print(array_nullo) 
# analogo per matrici come per ones

a = np.arange(1,20,2) 
print(a)

b = np.linspace(1,10,num=10) # unico caso in cui gli estremi sono entrambi inclusi
print(b)

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[0. 0. 0. 0. 0. 0.]
[ 1  3  5  7  9 11 13 15 17 19]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [38]:
c = np.array([1,2,4,7,0,-3,-20,18],)
np.sort(c)

array([-20,  -3,   0,   1,   2,   4,   7,  18])

In [40]:
d = np.concatenate((a,b))
d

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.,  1.,  2.,  3.,
        4.,  5.,  6.,  7.,  8.,  9., 10.])

In [44]:
print(np.shape(matrice_unit))
print(np.ndim(matrice_unit)) # mi dice il numero di assi dell'array
print(np.size(matrice_unit)) # mi dice gli elementi totali

(6, 6)
2
36


In [55]:
a = np.arange(6)
#e = a.reshape(3,2)
e = np.reshape(a, (3,2))
print(e)

[[0 1]
 [2 3]
 [4 5]]


In [58]:
print(a[-3]) # con il "-" conta gli elementi dall'ultimo

3


In [66]:
a = np.arange(100)
print(a[(a>=10) & (a<20)])

[10 11 12 13 14 15 16 17 18 19]


In [69]:
a = np.array([0,0,4,3,0,2,1])
i = np.nonzero(a)
print(a[i])

[4 3 2 1]


# ATTENZIONE

In [76]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [77]:
b = a[4:]
print(b)

[4 5 6 7 8 9]


In [78]:
b[0] = 99
print(b)

[99  5  6  7  8  9]


In [79]:
print(a)

[ 0  1  2  3 99  5  6  7  8  9]


In [80]:
# copia reale 
a = np.arange(10)
print(a)
b = a.copy()
#b = np.copy(a)
print(b)
b[0]=99
print(a,b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9] [99  1  2  3  4  5  6  7  8  9]


In [81]:
#oppure, ma meno elegante
a = np.arange(10)
print(a)
b = np.zeros(len(a))
b[:]=a[:] # se non metto le parentesi quadre non creo una copia ma un puntatore
print(b)
b[0]=99
print(a,b)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9] [99.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


# Operazioni algebra lineare

In [85]:
a = np.random.uniform(0,1,10) # genera 10 numeri distribuiti in maniera uniforme tra 0 e 1
print(a)
B = np.random.normal(0,1,(10,10)) # genera una matrice 10x10 con valori distribuiti come una Normale  con var=1 e media 0
print(B)

[0.87642868 0.70157236 0.70720348 0.77372653 0.63308646 0.8958424
 0.47395433 0.34574151 0.69792735 0.09261667]
[[-1.19978184e+00 -2.06082060e+00  9.96132367e-01 -1.60436307e+00
   2.59377050e-01 -1.44787653e-01  9.71175127e-01  1.20320962e+00
  -2.66215429e-01 -1.19602770e+00]
 [-8.01398024e-01 -8.15304903e-02 -4.82920708e-01  2.73470869e-01
  -1.67248114e+00  6.15484056e-01  6.22756560e-01 -4.83702634e-01
   3.97144859e-01 -1.63391826e-01]
 [-5.78598241e-01  1.60255852e+00 -5.70274980e-01  3.95531344e-01
   4.55581472e-01 -7.64261830e-02  1.90746889e+00 -4.40503559e-01
   1.01909901e+00  1.64143454e+00]
 [-2.23500522e-01 -4.23268269e-01 -1.79290334e+00  2.03100272e-01
  -8.76416272e-01 -2.26134905e-01  1.30937646e+00 -1.81262173e+00
  -1.40834686e+00 -8.11861133e-01]
 [ 3.65037650e-01  7.40446942e-01 -1.18933590e+00 -7.33057364e-01
   5.01601671e-01  6.46231369e-02 -4.66103026e-01 -1.43748347e-01
  -9.11455418e-01  6.03897425e-01]
 [ 8.49825735e-01  8.12325520e-01  1.16785824e+00  1.

In [88]:
a + B # somma il vettore colonna a tutte le colonne della matrice
a * B # fa il prodotto element wise del vettore per la matrice 

array([[-1.05152321e+00, -1.44581476e+00,  7.04468273e-01,
        -1.24133827e+00,  1.64208099e-01, -1.29706919e-01,
         4.60292656e-01,  4.15999514e-01, -1.85799028e-01,
        -1.10772100e-01],
       [-7.02368211e-01, -5.71995382e-02, -3.41523203e-01,
         2.11591667e-01, -1.05882517e+00,  5.51376716e-01,
         2.95158168e-01, -1.67236081e-01,  2.77178258e-01,
        -1.51328065e-02],
       [-5.07100092e-01,  1.12431076e+00, -4.03300448e-01,
         3.06033095e-01,  2.88422462e-01, -6.84658155e-02,
         9.04053138e-01, -1.52300367e-01,  7.11257068e-01,
         1.52024197e-01],
       [-1.95882267e-01, -2.96953317e-01, -1.26794747e+00,
         1.57144069e-01, -5.54847277e-01, -2.02581237e-01,
         6.20584641e-01, -6.26698581e-01, -9.82923792e-01,
        -7.51918727e-02],
       [ 3.19929465e-01,  5.19477106e-01, -8.41102486e-01,
        -5.67185932e-01,  3.17557227e-01,  5.78921463e-02,
        -2.20911547e-01, -4.96997712e-02, -6.36129664e-01,
         5.

In [92]:
C = np.random.normal(0,1,(5,10))
print(C)
print(np.shape(a*C)) # moltiplicazione element wise

[[ 0.16053969  1.15027006  1.40170454 -0.70695088 -1.080679   -0.04918908
  -0.47425104  1.77842563  1.27409283 -0.02141231]
 [ 0.80409918 -0.81394595 -0.8499165   1.35289445 -1.24601416  1.13097043
   0.70407552  0.2465398  -0.0708576  -1.17743181]
 [ 0.51286959 -0.28523441 -1.48799026 -0.38615742  0.60777564  0.65755376
  -0.33177505 -1.48151772  1.63346646 -0.51643199]
 [ 1.09421869 -0.56366059  1.33376048  1.55683876  1.11242437  2.01171428
  -0.42632092 -0.29531753 -0.8989578  -0.38024407]
 [ 0.38913677 -0.54125941 -1.38274293  0.435063   -0.51532185  1.7863757
  -0.48618882 -0.31852081 -0.48818481 -0.63774936]]
(5, 10)


In [98]:
D = np.dot(C,a) # moltiplicazione riga per colonna
print(D)

[ 1.94111735  1.06417203  0.2948703   4.25101888 -0.14621593]


$ a = a_\mu$ 

$ C = C^i_j$

$ D = C^i_j\cdot a_\mu = d_j $

In [100]:
E = np.dot(a,C.T)
print(E)

[ 1.94111735  1.06417203  0.2948703   4.25101888 -0.14621593]


In [ ]:
#trasposizione
C.T #metodo che restituisce la trasposta di C
np.transpose(C) # funzione equivalente

In [101]:
b = np.random.uniform(1,10,10)
c = np.random.uniform(1,10,10)
print(b*c)
print(np.dot(b,c))

[21.00232421  6.44041614 17.158001   27.32457742 48.24850885 33.45812214
  9.21330892 31.18252233 24.13708537 60.05804971]
278.22291608533607


In [103]:
a=np.array([1,2,3])
b=np.array([5,6,7])
(a+b)**2. - np.sqrt(a)

array([35.        , 62.58578644, 98.26794919])